hedges-work-order-hub/config/routes.rb
Rails.application.routes.draw do
root 'sessions#woh'

  resources :buildings
  resources :tenants
  resources :staff_members
  #* =================================================L O G  I N=====
  # get 'login', to: 'application#login'
  # CUSTOM ROUTE - USER CAN VISIT '/login' 

  # I WANT TO FOLLOW CHARLOTTE'S FLOW 
  #  IT'S LESS CONFUSING
  get 'login', to: 'sessions#new'
  # SHOW LOG-IN-VIEW TO USER WITH FORMS
  post 'login', to: 'sessions#create'
  # SUBMIT USER'S PARAMS FROM FORMS TO LOG THEM IN
  delete 'logout', to: 'sessions#destroy'
  # LOG THE USER OUT - DELETE THE USER'S SESSION[:ID]
#* ================================================================
#? ===================================OMNIAUTH L O G   I N==========
  get '/auth/:provider/callback' => 'sessions#omniauth'
  # GOOGLE SENDS A RESPONSE BACK WITH THIS - LOGIC INSIDE SESSIONS_CONTROLLER #OMNIAUTH METHOD
#? ================================================================
#? ===================================OMNIAUTH S I G N  U P==========
  get '/staff_members/:id/step_2' => 'staff_members#step_2'
  # PATCHES OVER TO /STAFF_MEMBER/:ID/EDIT
#? ================================================================
  get 'signup', to: 'staff_members#new'

  # =========================================HUB A C C E S S===========
  get 'hub', to: 'sessions#hub'

  # ====================================================================
                                              # N E S T E D [ R o u t e ]  
    # resources :apartments do
    #   resources :work_order, shallow: true
    # end     
  # IS REALLY GIVING \/
  # /:apartments/ [:new, :create, :show, :edit, :update, :destroy]
  # /:work_orders/, only: [:show, :edit, :update, :destroy]
  # /:apartments/ :work_orders/, only: [:index, :new, :create]
  
  
  resources :apartments do
    resources :work_orders, only: [:new, :create, :show, :index, :edit, :update, :destroy]
  end
  resources :work_orders, only: [:new, :create]

  # +            +            +            +            +            +

  resources :buildings do
    resources :work_orders, only: [:index]
  end

  # =====================================================================
  #                                       A CTIVE R ECORD S C O P E USAGE  
  get '/work_orders', to: 'work_orders#index'
  get '/work_orders/status_pending', to: 'work_orders#status_pending'
  # =====================================================================
end 

hedges-work-order-hub/app/models/work_order.rb
class WorkOrder < ApplicationRecord
    belongs_to :staff_member
    belongs_to :tenant, optional: true
    
    belongs_to :apartment, optional: true
    # belongs_to :building, optional: true
    validates :status, :content, :presence => true

    STATUS_OPTIONS = ["PENDING", "COMPLETE"]

    # ===========================================================
    # IF THIS WORK ORDER HAS A TENANT ATTACHED
    # USE FOR COLLECTION_SELECT data display
    def tenant_name=(name)
        # PASS IN THE NAME that you want to search the database for
        # CALLED WHEN WORKORDER is INITIALIZED w/ 'TENANT_NAME' FIELD
        self.tenant = Tenant.find_by(name: name)
    end

    def tenant_name
        # IF WORK ORDER has a TENANT
        self.tenant ? self.tenant.name : nil
    end
    # ===========================================================
    def tenant_display=(display)
        self.tenant = Tenant.find_by(:full_display => display)
    end
    def tenant_display
        self.tenant ? self.tenant.full_display : nil
    end
    # ===========================================================
    def self.pending_orders
        ##########INSERT LOGIC TO DESCIPHER @WORK_ORDERS = :STATUS = 'PENDING' 
        WorkOrder.where(:status => "PENDING")
    end
end

hedges-work-order-hub/app/controllers/work_orders_controller.rb
class WorkOrdersController < ApplicationController

    def new
        @work_order = WorkOrder.new
        @apt_toggle = ""
        if params[:apartment_id]
            @apt_toggle = params[:apartment_id]
            @apt = Apartment.find_by(params[:apartment_id])
        end
        render :new
    end

    def create

        
        @work_order = WorkOrder.new(work_order_params)
        @work_order.staff_member = current_staff_member
    
        if @work_order.save
            redirect_to apartment_work_order_path(@work_order.tenant.apartment, @work_order)
        else
            if params[:apartment_id]
                @apt_toggle = params[:apartment_id]
                @apt = Apartment.find_by(params[:apartment_id])
            end
            "work order CREATE failure"
            render :new
        end
    end

    def show
        @work_order = WorkOrder.find_by_id(params[:id])
    end

    def edit
        if params[:apartment_id]
            @work_order = WorkOrder.find_by(:id => params[:id])
            @apartment = Apartment.find_by_id(params[:apartment_id])
        else
            @work_order = WorkOrder.find_by_id(params[:id])
        end
    end

    def update
        @work_order = WorkOrder.find_by_id(params[:id])
        @work_order.update(work_order_params)

        @tenant = Tenant.find_by_name(params[:work_order][:tenant_name])
        @work_order.tenant_id = @tenant.id

        if @work_order.save
            redirect_to apartment_work_order_path(@work_order)
        else
            render :edit
        end

    end

    def destroy
        @work_order = WorkOrder.find_by_id(params[:id])
        @work_order.destroy
        redirect_to new_work_order_path
    end

    def index # FEATURES [[[NESTED ROUTE CONDITIONAL!!!]]]
        #'/APARTMENTS/:APARTMENT_ID/WORK_ORDERS'
    
        if params[:apartment_id]
            @apartment = Apartment.find_by(:id => params[:apartment_id])
            @work_orders = @apartment.work_orders
    
        
        #'/BUILDINGS/:BUILDING_ID/WORK_ORDERS'
        elsif params[:building_id]
            @building = Building.find_by_id(params[:building_id])
            @apartments = Apartment.find_by_building_id(@building.id)
            @work_orders = @apartments.work_orders # @work_orders = @building.work_orders <<<<< What I wanted to work :C
      
        #'/WORK_ORDERS'
        else
    
            @work_orders = WorkOrder.all
        end        
    end

    def status_pending
        # @work_orders = WorkOrder.where(:status => "PENDING")
        @work_orders = WorkOrder.pending_orders
        render :status_pending
    end

        private
            def work_order_params
                params.require(:work_order).permit(:content, :status, :solution, :solve_date, :worker, :staff_member_id, :tenant, :apartment_id, :tenant_id, :building_id)
            end
end 

hedges-work-order-hub/app/helpers/work_orders_helper.rb
module WorkOrdersHelper
end

hedges-work-order-hub/app/views/work_orders/_work_order.html.erb

<%= link_to "Work Order # : #{@work_order.id}", apartment_work_order_path(@work_order.tenant.apartment.id, @work_order.id) %>
<br>

    FILER: <%= @work_order.tenant.name %>
<ul> 
    <%= "• STATUS : #{@work_order.status}" %><br>
    <%= "• CONTENT : #{@work_order.content}" %><br>

    <%= "► SOLVE DATE : #{@work_order.solve_date}" unless @work_order.solve_date == nil || @work_order.solve_date == "" %>
    <%= "► SOLUTION : #{@work_order.solution}" unless @work_order.solution == nil || @work_order.solution == "" %>    
    <%= "► WORKER : #{@work_order.worker}" unless @work_order.worker == nil || @work_order.worker == "" %><br>
</ul>

        <%= link_to @work_order.tenant.apartment.short_address, apartment_path(@work_order.tenant.apartment.id) %>
        
        |

        <%if current_staff_member.id == @work_order.staff_member.id %>
            
                <%= link_to "EDIT Work Order ##{@work_order.id}", edit_apartment_work_order_path(@work_order.tenant.apartment_id, @work_order.id) %>
            
        <%end%>

      | REGISTRAR : 
      <%= link_to @work_order.staff_member.first_name + " " + @work_order.staff_member.last_name, staff_member_path(@work_order.staff_member) %> 
      |
      
    
<hr>

hedges-work-order-hub/app/views/work_orders/_work_orders.html.erb
<% @work_orders.each do |wo| %>

<%= link_to "Work Order # : #{wo.id}", apartment_work_order_path(wo.tenant.apartment.id, wo.id) %>
<br>

    FILER: <%= wo.tenant.name %>
<ul> 
    <%= "• STATUS : #{wo.status}" %><br>
    <%= "• CONTENT : #{wo.content}" %><br>

    <%= "► SOLVE DATE : #{wo.solve_date}" unless wo.solve_date == nil || wo.solve_date == "" %>
    <%= "► SOLUTION : #{wo.solution}" unless wo.solution == nil || wo.solution == "" %>    
    <%= "► WORKER : #{wo.worker}" unless wo.worker == nil || wo.worker == "" %><br>
</ul>

        <%= link_to wo.tenant.apartment.short_address, apartment_path(wo.tenant.apartment.id) %>
        
        |

        <%if current_staff_member.id == wo.staff_member.id %>
            
                <%= link_to "EDIT Work Order ##{wo.id}", edit_apartment_work_order_path(wo.tenant.apartment_id, wo.id) %>
            
        <%end%>

      | REGISTRAR : 
      <%= link_to wo.staff_member.first_name + " " + wo.staff_member.last_name, staff_member_path(wo.staff_member) %> 
      |
      
    
<hr>
<% end %>

hedges-work-order-hub/app/views/work_orders/edit.html.erb
<center>
<hr>
<%= "EDIT WORK ORDER # #{@work_order.id}" %>
<hr>
<%= "[#{@work_order.tenant.apartment.number}]" %>
<br>
<%= "#{@work_order.tenant.apartment.building.number}" %>
<%= "#{@work_order.tenant.apartment.building.street_address}" %>
<hr>
</center>

<%=form_with(model: @work_order, url: apartment_work_order_path(@work_order), method: "patch") do |f| %>

   
<div id="error_explanation">
    <% if @work_order.errors.any? %>

        <ul>
            <% @work_order.errors.full_messages.each do |m| %>
                <li>
                <%= m %>
                </li>
            <% end %>
        </ul>
        
    <% end %>
</div>
 





    <div>
    <%= f.label :tenant %>
    <%# DISPLAY ONLY THE TENANTS THAT LIVE INSIDE THAT SPECIFIC APARTMENT %>
    <%= f.collection_select :tenant_name, Tenant.where(:apartment_id => @work_order.tenant.apartment.id), :name, :name %>
    </div>

    <div>
    <%= f.label :status %>
    <%= f.collection_select(:status, WorkOrder::STATUS_OPTIONS, :to_s, :to_s) %>
    </div>

    <div>
    <%= f.label :content %>
    <%= f.text_area :content %>
    </div>

    <div>
    <%= f.label :solution %>
    <%= f.text_area :solution %>
    </div>

    <div>
    <%= f.label :solve_date %>
    <%= f.text_field :solve_date %>
    </div>

    <div>
    <%= f.label :worker %>
    <%= f.text_field :worker %>
    </div>

  <hr>
    <%= f.submit %>
  <hr>
<% end %>

<center>
<%= button_to "Delete Work Order", apartment_work_order_path(@work_order.tenant.apartment_id, @work_order.id), method: :delete %>
</center>
<hr>

hedges-work-order-hub/app/views/work_orders/index.html.erb
<hr><center>WORK ORDERS INDEX</center><hr>




<%= render partial: 'work_orders' %>

hedges-work-order-hub/app/views/work_orders/new.html.erb
<hr>
<center>Create a New Work Order Here!</center>
<hr>


<%= form_for [@apt, @work_order] do |f| %>

<div id="error_explanation">
    <% if @work_order.errors.any? %>

        <ul>
            <% @work_order.errors.full_messages.each do |m| %>
                <li>
                <%= m %>
                </li>
            <% end %>
        </ul>
        
    <% end %>
</div>

  
<div><%# (METHOD, COLLECTION, VALUE_METHOD, TEXT_METHOD, OPTIONS = { }, HTML_OPTIONS = { }) %>  
  Tenant:
    <% if @apt_toggle != "" %>
      <%= f.collection_select :tenant_id, Tenant.where(:apartment_id => @apt_toggle), :id, :full_display, {:prompt => "Please, select a tenant"} %>
    <% else %>
     <%= f.collection_select :tenant_id, Tenant.order(:full_display), :id, :full_display, {:prompt => "Please, select a tenant"}%>
    <% end %>
  <hr>
</div> 

    <div>
    <%= f.label :status %>
     <%= f.collection_select(:status, WorkOrder::STATUS_OPTIONS, :to_s, :to_s, {:prompt => "-"} ) %>
    </div>

    <div>
    <%= f.label :content %>
    <%= f.text_area :content %>
    </div>

    <div>
    <%= f.label :solution %>
    <%= f.text_area :solution %>
    </div>

    <div>
    <%= f.label :solve_date %>
    <%= f.text_field :solve_date %>
    </div>

    <div>
    <%= f.label :worker %>
    <%= f.text_field :worker %>
    </div>

<hr>
  <%= f.submit %>
<hr>
<% end %>


hedges-work-order-hub/app/views/work_orders/show.html.erb
<hr><center>
<%= "WORK ORDER # #{@work_order.id}" %>
</center><hr>



        <%= render partial: 'work_order' %>




<hr>
<% if current_staff_member.id == @work_order.staff_member.id %>
    <%= link_to "Edit This Work Order's Details", edit_apartment_work_order_path(@work_order.tenant.apartment_id, @work_order.id) %>
<% end %>

<hr>
<%= button_to "Delete Work Order", apartment_work_order_path(@work_order.tenant.apartment_id, @work_order.id), method: :delete %>
<hr>

<center> GO TO : <%= link_to "Work Order Index", work_orders_path %> </center>

<hr>

<center> GO TO : <%= link_to "Apartment", apartment_path(@work_order.tenant.apartment) %> </center>


hedges-work-order-hub/app/views/work_orders/status_pending.html.erb
<center>
<hr>
WORK ORDERS
<br>
    <% if @work_orders %>
        <%= "(#{@work_orders.count})" %>
    <% else %>
        (0)
    <% end %>
<br>
STATUS PENDING - NEED ACTION!
<hr>
</center>

<% if @work_orders %>
    <center>
    <%=render partial: 'work_orders'%>
    </center>
<% else %>
    <center><%= link_to "Create a new Work Order", new_work_order_path %></center>
<% end %>
