hedges-work-order-hub/config/routes.rb
Rails.application.routes.draw do
root 'sessions#woh'

  resources :buildings
  resources :tenants
  resources :staff_members
  #* =================================================L O G  I N=====
  # get 'login', to: 'application#login'
  # CUSTOM ROUTE - USER CAN VISIT '/login' 

  # I WANT TO FOLLOW CHARLOTTE'S FLOW 
  #  IT'S LESS CONFUSING
  get 'login', to: 'sessions#new'
  # SHOW LOG-IN-VIEW TO USER WITH FORMS
  post 'login', to: 'sessions#create'
  # SUBMIT USER'S PARAMS FROM FORMS TO LOG THEM IN
  delete 'logout', to: 'sessions#destroy'
  # LOG THE USER OUT - DELETE THE USER'S SESSION[:ID]
#* ================================================================
#? ===================================OMNIAUTH L O G   I N==========
  get '/auth/:provider/callback' => 'sessions#omniauth'
  # GOOGLE SENDS A RESPONSE BACK WITH THIS - LOGIC INSIDE SESSIONS_CONTROLLER #OMNIAUTH METHOD
#? ================================================================
#? ===================================OMNIAUTH S I G N  U P==========
  get '/staff_members/:id/step_2' => 'staff_members#step_2'
  # PATCHES OVER TO /STAFF_MEMBER/:ID/EDIT
#? ================================================================
  get 'signup', to: 'staff_members#new'

  # =========================================HUB A C C E S S===========
  get 'hub', to: 'sessions#hub'

  # ====================================================================
                                              # N E S T E D [ R o u t e ]  
    # resources :apartments do
    #   resources :work_order, shallow: true
    # end     
  # IS REALLY GIVING \/
  # /:apartments/ [:new, :create, :show, :edit, :update, :destroy]
  # /:work_orders/, only: [:show, :edit, :update, :destroy]
  # /:apartments/ :work_orders/, only: [:index, :new, :create]
  
  
  resources :apartments do
    resources :work_orders, only: [:new, :create, :show, :index, :edit, :update, :destroy]
  end
  resources :work_orders, only: [:new, :create]

  # +            +            +            +            +            +

  resources :buildings do
    resources :work_orders, only: [:index]
  end

  # =====================================================================
  #                                       A CTIVE R ECORD S C O P E USAGE  
  get '/work_orders', to: 'work_orders#index'
  get '/work_orders/status_pending', to: 'work_orders#status_pending'
  # =====================================================================
end 

hedges-work-order-hub/app/models/staff_member.rb
class StaffMember < ApplicationRecord
    has_many :work_orders
    # ============================================================
    has_secure_password
    # ADDS #PASSWORD & #PASSWORD_CONFIRMATION | EXPECTS :PASSWORD_DIGEST | 'BCRYPT' GEM
    # ADDS HOOKS - #BEFORE_SAVE : COMPARES PASSWORD & PASSWORD_CONFIRMATION
    # ============================================================
    validates :first_name, :last_name, :presence => true
    




    def self.find_with_omniauth_login(response)
        # I WISH TO CARRY THIS FROM A BUTTON PRESS - session[:signup_or_login] = "login"
        return StaffMember.find_by(:uid => response[:uid], :provider => response[:provider])
# byebug
    end




    def self.new_from_omniauth(response) #since this came from a button that is for signup&login      
            sm = StaffMember.new(:uid => response[:uid], :provider => response[:provider])
             sm.first_name = response[:info][:first_name]
             sm.last_name = response[:info][:last_name]
             sm.email = response[:info][:email]
             sm.password = SecureRandom.hex(15) #USER NEVER SEES THIS SO WHAT'S THE POINT
             sm.password_confirmation = sm.password #USER NEVER SEES THIS SO WHAT'S THE POINT   
             sm
    end


    

end 

hedges-work-order-hub/app/controllers/staff_members_controller.rb
class StaffMembersController < ApplicationController
    # ============================================================
    # REQUIRE THAT A USER BE LOGGED IN (THE '#REQUIRE_LOGIN' BEFORE ANYTHING ELSE FOR ACTIONS
    # before_action :require_login
    # EXCEPT FOR THE INDEX ACTION
    # skip_before_action :require_login, only: [:index]
    # ============================================================

    def show
        @staff_member = StaffMember.find(params[:id])
    end
    
    def index
         @staff_members = StaffMember.all
    end
#SIGN UP A NEW STAFF MEMBER
    def new
        
        
        @staff_member = StaffMember.new
        # ∟ PREPOPULATES WITH FORM_FOR - PREPOPULATE WITH USER'S INPUTS
        render :new
    end

    # POST INFO FROM THE NEW ROUTE TO CREATE A NEW STAFF_MEMBER
    def create

        @staff_member = StaffMember.new(staff_member_params)

        if @staff_member.valid?
            @staff_member.save
            session[:staff_member_id] = @staff_member.id
            redirect_to staff_member_path(@staff_member)
        else
            render :new
        end
        
    end

    def edit
        @staff_member = StaffMember.find_by_id(params[:id])
    end

    def update
        @staff_member = StaffMember.find_by_id(params[:id])

        if params[:staff_member][:password] && params[:staff_member][:password] == params[:staff_member][:password_confirmation]
            @staff_member.update(staff_member_params)
            redirect_to staff_member_path(@staff_member)
        elsif params[:staff_member][:password] && params[:staff_member][:password] != params[:staff_member][:password_confirmation]
            flash[:error] = "New Password and Confirmation error!"
            render :edit
        else
            @staff_member.update(staff_member_params)
            render :edit
        end

    end

    def destroy
        @staff_member = StaffMember.find_by_id(params[:id])
        @staff_member.destroy
        redirect_to signup_path

    end

    def step_2
        #DOES THE URL SEGMENT HAVE A MATCH IN THE DB
        @staff_member = StaffMember.find_by_id(params[:id])
        # CHECK THE SESSION..IF THERE'S AN ID THERE
        @smid = session[:staff_member_id]

        if @staff_member.id == @smid
            render :step_2
        else 
            redirect_to :new
        end
    end

        private
            def staff_member_params
                params.require(:staff_member).permit(:first_name, :last_name,
                                                        :position, :email,
                                                        :uid, :provider,
                                                        :password, :password_confirmation)
            end

            # def require_login
            #     return head(:forbidden) unless session.include? :user_id
            # end


end

hedges-work-order-hub/app/helpers/staff_members_helper.rb
module StaffMembersHelper
end

hedges-work-order-hub/app/views/staff_members/edit.html.erb
<center><hr> STAFF MEMBER PROFILE <hr> EDIT <hr></center> 

<%= form_for(@staff_member) do |f| %>

<% if flash[:error] %>
<hr>
    <%= flash[:error] %>
<hr>
<% end %>

<div id="error_explanation">
    <% if @staff_member.errors.any? %>

        <ul>
            <% @staff_member.errors.full_messages.each do |m| %>
                <li>
                <%= m %>
                </li>
            <% end %>
        </ul>
        
    <% end %>
</div>

<div>
<%= f.label :first_name %>
<%= f.text_field :first_name, :placeholder => "Jane" %>

<%= f.label :last_name %>
<%= f.text_field :last_name, placeholder: "Doe" %>
<div>


<%= f.label :email %>
<%= f.email_field :email, :placeholder => "abc@123.edu" %>

<%# ===================================================== %>
<div>
    

    <div>
    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
    </div><br>

    
</div>


<%# ===================================================== %>
<hr>
    <%= f.label :position %>
    <%= f.text_field :position, placeholder: "---" %>   
<hr>
<div>
    <%= f.submit %>
</div>
    <hr>
    
    
<% end %>
     
<%# ========================================================= %>
<center>
<hr>
    <%= button_to "Destroy Account!", staff_member_path(@staff_member.id), method: :delete %>

hedges-work-order-hub/app/views/staff_members/index.html.erb
<hr>
<center><h1>STAFF MEMBERS INDEX PAGE</h1></center>
<hr>



<ul>
<% @staff_members.each do |staff_m| %>
    <li>
    <%= link_to "#{staff_m.first_name.capitalize} #{staff_m.last_name.capitalize}", staff_m %>
    <%= staff_m.position %>
    </li>
<% end %>
</ul>

hedges-work-order-hub/app/views/staff_members/new.html.erb
<div style="text-align:right;">
    The Hedges- W O R K  |  O R D E R  |  H U B 
</div>

<hr><center>Sign Up Here!!!<hr>Create A New Staff Member</center><hr>

<%# <form action="/staff_members" method="POST"> %>
<%# CREATE FORM THAT ON SUBMISSION %>
<%# SENDS A POST REQUEST TO THE SERVER %>
<%# TO THE DATABASE TO CREATE AN INSTANCE OF THE STAFFMEMBER MODEL %>



    <%= form_for(@staff_member) do |f| %>
<div id="error_explanation">
    <% if @staff_member.errors.any? %>

        <ul>
            <% @staff_member.errors.full_messages.each do |m| %>
                <li>
                <%= m %>
                </li>
            <% end %>
        </ul>
        
    <% end %>
</div>

<div>
<%= f.label :first_name %>
<%= f.text_field :first_name, :placeholder => "Jane" %>

<%= f.label :last_name %>
<%= f.text_field :last_name, placeholder: "Doe" %>
<div>


<%= f.label :email %>
<%= f.email_field :email, :placeholder => "abc@123.edu" %>

<%# ===================================================== %>
<div>
    

    <div>
    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
    </div><br>

    
</div>


<%# ===================================================== %>
    <hr>
    <%= f.label :position %>
    <%= f.text_field :position, placeholder: "---"%>   
    <hr>
    
    
<div>
    <%= f.submit %>
</div>
<% end %> 
    
<hr><center>
OR
<br>
SIGN UP WITH 3RD PARTY CREDENTIALS
<br>

    <%= button_to "GMAIL", '/auth/google_oauth2' %>
</center><hr>    
   
    

hedges-work-order-hub/app/views/staff_members/show.html.erb
<% if flash[:message] %>
    <%= flash[:message] %>
<% end %>

<% if flash[:error] %>
    <%= flash[:error] %>
<% end %>

<hr>
<center>STAFF MEMBER PROFILE</center>
<hr>

<br>
<%= @staff_member.first_name %>
<%= @staff_member.last_name %><br>
<%= @staff_member.email %><br>
<%= @staff_member.position %><br>
<hr>

<%# =================================== %>
<center>
Go To : <%= link_to "Work Order Hub", '/hub' %>
</center>
<hr>
<%# =================================== %>
<% if current_staff_member.id == @staff_member.id %>
    <%= link_to "Edit Staff Member Details", edit_staff_member_path %>
<% end %>
<hr>
<%# =================================== %>
<%= link_to("Log out!", '/logout', method: :delete) %>
<%# =================================== %>


hedges-work-order-hub/app/views/staff_members/step_2.html.erb
<hr>
    STEP 2 IN THE SIGN UP PROCESS!<br>
    WHEN USING 3RD PARTY AUTHENTICATION<br>
    <h2>PLEASE, CONTINUE THIS SIGNUP PROCESS</h2>
<hr>
<%= form_for @staff_member do |f| %>

   <%= f.label :first_name %>:<br>  <%= @staff_member.first_name %><br>
   <%= f.label :last_name %>:<br>  <%= @staff_member.last_name %><br>
   <%= f.label :email %>:<br>   <%= @staff_member.email %><br>
<br>


    <%= f.label :position %>
    <%= f.text_field :position, required: true%>
<div>
    <%= f.submit "update this object for more data attribute values" %>
</div>
<% end %>