hedges-work-order-hub/config/routes.rb
Rails.application.routes.draw do
root 'sessions#woh'

  resources :buildings
  resources :tenants
  resources :staff_members
  #* =================================================L O G  I N=====
  # get 'login', to: 'application#login'
  # CUSTOM ROUTE - USER CAN VISIT '/login' 

  # I WANT TO FOLLOW CHARLOTTE'S FLOW 
  #  IT'S LESS CONFUSING
  get 'login', to: 'sessions#new'
  # SHOW LOG-IN-VIEW TO USER WITH FORMS
  post 'login', to: 'sessions#create'
  # SUBMIT USER'S PARAMS FROM FORMS TO LOG THEM IN
  delete 'logout', to: 'sessions#destroy'
  # LOG THE USER OUT - DELETE THE USER'S SESSION[:ID]
#* ================================================================
#? ===================================OMNIAUTH L O G   I N==========
  get '/auth/:provider/callback' => 'sessions#omniauth'
  # GOOGLE SENDS A RESPONSE BACK WITH THIS - LOGIC INSIDE SESSIONS_CONTROLLER #OMNIAUTH METHOD
#? ================================================================
#? ===================================OMNIAUTH S I G N  U P==========
  get '/staff_members/:id/step_2' => 'staff_members#step_2'
  # PATCHES OVER TO /STAFF_MEMBER/:ID/EDIT
#? ================================================================
  get 'signup', to: 'staff_members#new'

  # =========================================HUB A C C E S S===========
  get 'hub', to: 'sessions#hub'

  # ====================================================================
                                              # N E S T E D [ R o u t e ]  
    # resources :apartments do
    #   resources :work_order, shallow: true
    # end     
  # IS REALLY GIVING \/
  # /:apartments/ [:new, :create, :show, :edit, :update, :destroy]
  # /:work_orders/, only: [:show, :edit, :update, :destroy]
  # /:apartments/ :work_orders/, only: [:index, :new, :create]
  
  
  resources :apartments do
    resources :work_orders, only: [:new, :create, :show, :index, :edit, :update, :destroy]
  end
  resources :work_orders, only: [:new, :create]

  # +            +            +            +            +            +

  resources :buildings do
    resources :work_orders, only: [:index]
  end

  # =====================================================================
  #                                       A CTIVE R ECORD S C O P E USAGE  
  get '/work_orders', to: 'work_orders#index'
  get '/work_orders/status_pending', to: 'work_orders#status_pending'
  # =====================================================================
end 

hedges-work-order-hub/app/models/tenant.rb
class Tenant < ApplicationRecord
    validates :first_name, :last_name, :phone, :presence => true
    validates :phone, numericality: true, length: { is: 10 }
    before_validation :full_displayify

    belongs_to :staff_member
    has_many :work_orders

    # belongs_to :building
    belongs_to :apartment



    private
    def full_displayify
        self.full_display = "#{self.apartment.building.number}-#{self.apartment.number} : #{self.name}"
    end
    
end

hedges-work-order-hub/app/controllers/tenants_controller.rb
class TenantsController < ApplicationController
  def new
    @tenant = Tenant.new
  end

  def create
    @tenant = Tenant.new(tenant_params)
    @tenant.staff_member_id = current_staff_member.id.to_i
    @tenant.name = "#{params[:tenant][:first_name]} #{params[:tenant][:last_name]}"
  
    if @tenant.save
      redirect_to apartment_path(@tenant.apartment)
    else
      "TENANT #CREATE FAILURE"
      render :new
    end
  end

  def show
    @tenant = Tenant.find_by_id(params[:id])
  end

  def index
    @tenants = Tenant.all
  end

  def edit
    @tenant = Tenant.find_by_id(params[:id])
  end

  def update
    @tenant = Tenant.find_by_id(params[:id])
    @tenant.update(tenant_params)
    if @tenant.save
      redirect_to tenant_path(@tenant)
    else
      render :edit
    end
  end

    private
      def tenant_params
        params.require(:tenant).permit(:first_name, :last_name, :phone, :name, :staff_member_id, :tenant_id, :apartment_id, :building_id)
      end
end

hedges-work-order-hub/app/helpers/tenants_helper.rb
module TenantsHelper
end

hedges-work-order-hub/app/views/tenants/_form.html.erb
<%= form_for(@tenant) do |f| %>

<div id="error_explanation">
    <% if @tenant.errors.any? %>

        <ul>
            <% @tenant.errors.full_messages.each do |m| %>
                <li>
                <%= m %>
                </li>
            <% end %>
        </ul>
        
    <% end %>
</div>

     
    <%= f.collection_select :apartment_id, Apartment.order(:long_address), :id, :long_address, {:prompt => "Please, select an apartment"}, {:required => true} %>
    <br>

    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
    <br>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
    <br>
    <%= f.label :phone %>
    <%= f.telephone_field :phone %>
    <br>
    <%= f.submit %>
<% end %>

hedges-work-order-hub/app/views/tenants/_tenants.html.erb
<%# ITERATE THROUGH @'D TENANT.ALL %>
<% @tenants.each do |tenant| %>
<hr>
    FIRST NAME : <%= tenant.first_name %><br>
    LAST NAME : <%= tenant.last_name %><br>
    REGISTRAR : <%= tenant.staff_member.id.to_s + " - " + tenant.staff_member.first_name + " " + tenant.staff_member.last_name %><br>
    BUILDING : <%= tenant.apartment.building.number + " " + tenant.apartment.building.street_address %><br>
    APARTMENT : <%= tenant.apartment.number %><br>

    <%= link_to "View #{tenant.first_name}'s Tenant Profile", tenant_path(tenant) %>
<hr>
<% end %>

hedges-work-order-hub/app/views/tenants/create.html.erb
<h1>Tenants#create</h1>
<p>Find me in app/views/tenants/create.html.erb</p>

hedges-work-order-hub/app/views/tenants/edit.html.erb
<center>
<hr>
    EDIT TENANT REDORDS
<hr>
    TENANT #[<%= @tenant.id %>]
<hr>
</center>

<%= render partial: 'form' %>

hedges-work-order-hub/app/views/tenants/index.html.erb
<center><hr>TENANTS INDEX<hr></center>

<%= render "tenants" %>
<%# RENDER THE PARTIAL '/VIEWS/TENANTS/_TENANTS.HTML.ERB' %>

hedges-work-order-hub/app/views/tenants/new.html.erb
<hr>
<center>
CREATE A NEW TENANT HERE!
</center>
<hr>

    <%= render 'form' %> 

hedges-work-order-hub/app/views/tenants/show.html.erb
<center>
<hr>
TENANT INFORMATION
<hr>
    <%= @tenant.first_name %> <%= @tenant.last_name %><br>
    [<%= @tenant.apartment.number %>]<br>
    <%= @tenant.apartment.building.number + " " + @tenant.apartment.building.street_address %><br>
    <%= link_to "View Apartment", apartment_path(@tenant.apartment) %>
<hr>

    Telephone:<%=@tenant.phone%>

<hr>
</center>

<%= link_to "Edit Tenant Details", edit_tenant_path(@tenant) %>

hedges-work-order-hub/app/views/tenants/update.html.erb
<h1>Tenants#update</h1>
<p>Find me in app/views/tenants/update.html.erb</p>