hedges-work-order-hub/config/routes.rb
Rails.application.routes.draw do
root 'sessions#woh'

  resources :buildings
  resources :tenants
  resources :staff_members
  #* =================================================L O G  I N=====
  # get 'login', to: 'application#login'
  # CUSTOM ROUTE - USER CAN VISIT '/login' 

  # I WANT TO FOLLOW CHARLOTTE'S FLOW 
  #  IT'S LESS CONFUSING
  get 'login', to: 'sessions#new'
  # SHOW LOG-IN-VIEW TO USER WITH FORMS
  post 'login', to: 'sessions#create'
  # SUBMIT USER'S PARAMS FROM FORMS TO LOG THEM IN
  delete 'logout', to: 'sessions#destroy'
  # LOG THE USER OUT - DELETE THE USER'S SESSION[:ID]
#* ================================================================
#? ===================================OMNIAUTH L O G   I N==========
  get '/auth/:provider/callback' => 'sessions#omniauth'
  # GOOGLE SENDS A RESPONSE BACK WITH THIS - LOGIC INSIDE SESSIONS_CONTROLLER #OMNIAUTH METHOD
#? ================================================================
#? ===================================OMNIAUTH S I G N  U P==========
  get '/staff_members/:id/step_2' => 'staff_members#step_2'
  # PATCHES OVER TO /STAFF_MEMBER/:ID/EDIT
#? ================================================================
  get 'signup', to: 'staff_members#new'

  # =========================================HUB A C C E S S===========
  get 'hub', to: 'sessions#hub'

  # ====================================================================
                                              # N E S T E D [ R o u t e ]  
    # resources :apartments do
    #   resources :work_order, shallow: true
    # end     
  # IS REALLY GIVING \/
  # /:apartments/ [:new, :create, :show, :edit, :update, :destroy]
  # /:work_orders/, only: [:show, :edit, :update, :destroy]
  # /:apartments/ :work_orders/, only: [:index, :new, :create]
  
  
  resources :apartments do
    resources :work_orders, only: [:new, :create, :show, :index, :edit, :update, :destroy]
  end
  resources :work_orders, only: [:new, :create]

  # +            +            +            +            +            +

  resources :buildings do
    resources :work_orders, only: [:index]
  end

  # =====================================================================
  #                                       A CTIVE R ECORD S C O P E USAGE  
  get '/work_orders', to: 'work_orders#index'
  get '/work_orders/status_pending', to: 'work_orders#status_pending'
  # =====================================================================
end 

hedges-work-order-hub/app/models/apartment.rb
class Apartment < ApplicationRecord
validates :number, presence: true 
    belongs_to :building

    before_validation :short_addressify
    # before_save :short_addressify
    before_validation :long_addressify
    
    # TENANT join table
    has_many :tenants
    has_many :work_orders, through: :tenants

    accepts_nested_attributes_for :work_orders

    # PLUG IN the FORMULA AND THE STUFF
        private
        def short_addressify
            self.short_address = self.building.number + "-" + self.number
        end
         
        def long_addressify
            self.long_address = "#{self.building.number}-#{self.number} #{self.building.street_address}"
        end
end

hedges-work-order-hub/app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController

    def index
        @apartments = Apartment.all
    end

    def show
        @apartment = Apartment.find_by_id(params[:id])
        @tenants = Tenant.where(:apartment_id => @apartment.id)

        # @work_orders = WorkOrder.where(tenant.apartment.id => @apartment.id)
        @work_orders = @apartment.work_orders
        # @work_orders = Tenant.find(:apartment_id => params)
        # APARTMENTS LOOK THROUGH TENANTS 
        # GRAB ALL THE TENANTS WITH SELFS APTID
        # APARTMENTS LOOK THROUGH WORK ORDERS
        #@work_orders = WorkOrder.where(:tenant_id => @apartment) # WHY THE HECK DOES THIS WORK  !!!!!!!!!!!!!!!!!!!!!!!!
        # @work_orders = Apartment.find(params[:apartment_id].work_orders)
            #BREAKS if NOTHING is found
            # byebug
    end
end

hedges-work-order-hub/app/views/apartments/_apartment.html.erb

[<%= @apartment.number %>]
<br>
<%= @apartment.building.number + " " + @apartment.building.street_address %>

hedges-work-order-hub/app/views/apartments/index.html.erb
<center>
<hr>
APARTMENTS INDEX
<hr>
</center>

<%@apartments.each do |apt|%>
<%= link_to "#{apt.long_address}", apartment_path(apt) %>
|
<%= link_to "New Work Order", new_apartment_work_order_path(apt) %><br>
<hr>
<%end%>

hedges-work-order-hub/app/views/apartments/show.html.erb
<center>
<hr>
    APARTMENT
<br>
    <%= render 'apartment' %>
<hr>

<%= @tenants.count %> TENANT(S)
<br>
    <% @tenants.each do |t| %>
        
        ▬<%= link_to t.name, tenant_path(t) %>▬
        <br>
    <% end %>

<%= link_to "Register New Tenant", new_tenant_path %>



    <hr>

<%= @work_orders.count %> WORK ORDER(S) ON RECORD
<br>
<%= link_to "New Work Order", new_apartment_work_order_path(@apartment) %>
<hr>

</center>




    <%=render partial: 'work_orders/work_orders'%>